version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - .db_data/db.sqlite3:/db.sqlite3
    env_file:
      - ./.env
    ports:
      - 8000:8000


